title: "Titanic - Machine learning from disaster"
description: "In this project, we will predict the sorts of people who were likely to survive within the Titanic. Our main objective is to apply machine learning to predict which passengers survived the tragedy."
theme: jekyll-theme-cayman
